spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ems
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        ddl-auto: update
    open-in-view: false